eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@www.lin.com:8760/eureka/,http://root:123456@www.lin.com:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: consumer-user1