eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@www.lin.com:8760/eureka/, http://root:123456@www.lin.com:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: provider-hi
