server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@www.lin.com:8761/eureka/, http://root:123456@www.lin.com:8760/eureka/

spring:
  application:
    name: provider-hi
  security:
    user:
      name: root
      password: 123456