server:
  port: 8760

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@www.lin.com:8761/eureka/
  server:
      enable-self-preservation: false
spring:
  security:
    user:
      name: root
      password: 123456